# char=input('enter the elemnt ')
# print(f"{char}      {char}")
# print(f" {char}    {char}")
# print(f"  {char}  {char}")
# print(f"   {char}{char}")
# print(f"  {char}  {char}")
# print(f" {char}    {char}")
# print(f"{char}      {char}")
char=input('enter the element')
sp=' '
print(f"{char}{char}{char}{char}")
print(f"{sp*3}{char}")
print(f"{sp*2}{char}{sp*1}")
print(f"{sp*1}{char}{sp*2}")  
print(f"{char}{char}{char}{char}")